
using System.Collections.Generic;
using System.Linq;
using BOTF3D.UI;
using UnityEngine;
using BOTF3D.Combat;
using BOTF3D.Civilization;
using BOTF3D.Galaxy;
using BOTF3D.Audio;
using FischlWorks_FogWar;



namespace BOTF3D.Core
{
    public class TechManager : MonoBehaviour, IManager
    {
        public void Initialize() {}
        public void Cleanup() {}
        public static TechManager Instance;

        [SerializeField] private int techPointsPerResearchCenterPerTurn = 1;

        // ═══════════════════════════════════════════════════════════════════════════════════════
        // Phase II tech tree: weighted-parallel branch-priority research (TechTree_Phase2_Design.md
        // §2a, §6, §8 II.2). Majors only (§1) - minors keep the flat Phase I path in
        // ProcessMinorRaceResearch, untouched by any of this.
        // ═══════════════════════════════════════════════════════════════════════════════════════

        // All 84 authored TechDefSO assets (Assets/SO/TechDefSO/, generated by TechDefSOImporter).
        // Populated in the Editor via BOTF > Fix > Populate TechDefSO List in PersistentScene
        // (mirrors StarSysSOListPopulator's convention) rather than Resources.LoadAll, so these
        // assets are serialized into the scene/build without needing a Resources folder.
        [SerializeField] private List<TechDefSO> allTechDefs = new();

        private static readonly TechFieldEnum[] SharedFields =
        {
            TechFieldEnum.Propulsion, TechFieldEnum.Tactical, TechFieldEnum.Ordnance,
            TechFieldEnum.Science, TechFieldEnum.Intelligence
        };

        // §2a's placeholder split: Branch F's always-on share, then rank 1..5 of the player's
        // SharedBranchPriority order. Tunable in the §8 II.5 balance pass - not fixed by this file.
        // Public so the priority-ranking UI can display each row's live % share (§8 II.4).
        public const float FactionUniqueShare = 0.15f;
        public static readonly float[] RankShares = { 0.34f, 0.21f, 0.13f, 0.10f, 0.07f };

        private Dictionary<string, TechDefSO> techDefsById;
        private Dictionary<TechFieldEnum, List<TechDefSO>> sharedDefsByField; // sorted by Tier
        private Dictionary<CivEnum, List<TechDefSO>> uniqueDefsByCiv;         // sorted by Tier

        private void EnsureLookupsBuilt()
        {
            if (techDefsById != null) return;

            techDefsById = new Dictionary<string, TechDefSO>();
            sharedDefsByField = new Dictionary<TechFieldEnum, List<TechDefSO>>();
            uniqueDefsByCiv = new Dictionary<CivEnum, List<TechDefSO>>();

            foreach (var def in allTechDefs)
            {
                if (def == null) continue;
                techDefsById[def.Id] = def;

                if (def.IsShared)
                {
                    if (!sharedDefsByField.TryGetValue(def.Field, out var list))
                        sharedDefsByField[def.Field] = list = new List<TechDefSO>();
                    list.Add(def);
                }
                else
                {
                    if (!uniqueDefsByCiv.TryGetValue(def.RestrictedToCiv, out var list))
                        uniqueDefsByCiv[def.RestrictedToCiv] = list = new List<TechDefSO>();
                    list.Add(def);
                }
            }

            foreach (var list in sharedDefsByField.Values) list.Sort((a, b) => a.Tier.CompareTo(b.Tier));
            foreach (var list in uniqueDefsByCiv.Values) list.Sort((a, b) => a.Tier.CompareTo(b.Tier));

            if (techDefsById.Count == 0)
                Debug.LogWarning("TechManager: allTechDefs is empty - run Tools > Import TechDefSO CSVs " +
                    "then BOTF > Fix > Populate TechDefSO List in PersistentScene.");
        }

        /// <summary>
        /// A branch's current pick: its own lowest-tier tech not yet in ResearchedTechIds, ignoring
        /// whether that tech's TechPointsThreshold has been reached yet (§2a's pre-banking rule - a
        /// branch keeps banking toward its next tech even before that tier unlocks, rather than
        /// idling). A manual pin (StartResearch) overrides this as long as it's still unresearched
        /// and belongs to this field. Returns null only once every tech in the branch (or, for
        /// FactionUnique, every one of this civ's Branch F researched entries) is complete - the
        /// terminal state §2a's income split redistributes around.
        /// </summary>
        public TechDefSO GetBranchTarget(CivController civ, TechFieldEnum field)
        {
            if (civ?.CivData == null) return null;
            EnsureLookupsBuilt();
            // Idempotent - guarantees the free Tier-0 innate reads as researched even if this civ
            // is queried (e.g. by a UI browser) before its first ApplyBranchPriorityIncome tick,
            // not just after (that call site keeps its own copy too - harmless, same guard).
            EnsureInnateTechApplied(civ);

            if (civ.CivData.ManualTechPinByField != null &&
                civ.CivData.ManualTechPinByField.TryGetValue(field, out string pinnedId) &&
                techDefsById.TryGetValue(pinnedId, out var pinned) &&
                !civ.CivData.ResearchedTechIds.Contains(pinnedId))
            {
                return pinned;
            }

            List<TechDefSO> candidates = field == TechFieldEnum.FactionUnique
                ? (uniqueDefsByCiv.TryGetValue(civ.CivData.CivEnum, out var u) ? u : null)
                : (sharedDefsByField.TryGetValue(field, out var s) ? s : null);
            if (candidates == null) return null;

            foreach (var def in candidates)
            {
                if (def.UnlockMode == TechUnlockMode.InnateFromStart) continue; // never queued, §5
                if (!civ.CivData.ResearchedTechIds.Contains(def.Id))
                    return def;
            }
            return null;
        }

        /// <summary>
        /// Returns every TechDefSO in this branch (or, for FactionUnique, this civ's own 7 Branch F
        /// entries: the free innate + 6 researched), sorted by Tier ascending - a read-only listing
        /// for a full tech-tree browser UI (§8 II.4), as opposed to GetBranchTarget's single "what's
        /// next" pick. Includes InnateFromStart entries, unlike GetBranchTarget - a browser should
        /// still show a civ's free ability, just already marked researched. Returns a copy, safe for
        /// a caller to hold onto without risking TechManager's own lookup lists.
        /// </summary>
        public List<TechDefSO> GetBranchTechs(CivController civ, TechFieldEnum field)
        {
            if (civ?.CivData == null) return null;
            EnsureLookupsBuilt();
            EnsureInnateTechApplied(civ);

            List<TechDefSO> source = field == TechFieldEnum.FactionUnique
                ? (uniqueDefsByCiv.TryGetValue(civ.CivData.CivEnum, out var u) ? u : null)
                : (sharedDefsByField.TryGetValue(field, out var s) ? s : null);

            return source == null ? null : new List<TechDefSO>(source);
        }

        /// <summary>
        /// Manual pin: target this specific tech in place of its branch's natural GetBranchTarget
        /// pick, until it completes (§2a). Always succeeds - there is no concurrency cap to check
        /// against (Research Centers scale income, not how many branches can progress, §2).
        /// </summary>
        public void StartResearch(CivController civ, string techId)
        {
            if (civ?.CivData == null || string.IsNullOrEmpty(techId)) return;
            EnsureLookupsBuilt();

            if (!techDefsById.TryGetValue(techId, out var def))
            {
                Debug.LogWarning($"StartResearch: unknown TechDefSO id '{techId}'.");
                return;
            }

            civ.CivData.ManualTechPinByField ??= new Dictionary<TechFieldEnum, string>();
            civ.CivData.ManualTechPinByField[def.Field] = techId;
        }

        /// <summary>
        /// Sets/reorders the civ's 1st-5th priority over the 5 shared branches (§2a). Always
        /// succeeds and never touches BankedTechPointsByTechId - re-ranking only changes how fast
        /// each branch accrues from this point on.
        /// </summary>
        public void SetBranchPriority(CivController civ, List<TechFieldEnum> orderedSharedFields)
        {
            if (civ?.CivData == null || orderedSharedFields == null) return;

            var valid = orderedSharedFields.Where(f => f != TechFieldEnum.FactionUnique).Distinct().ToList();
            if (valid.Count != SharedFields.Length)
            {
                Debug.LogWarning($"SetBranchPriority: expected all 5 shared branches exactly once, got [{string.Join(",", orderedSharedFields)}].");
                return;
            }

            civ.CivData.SharedBranchPriority = valid;
        }

        private void EnsureBranchPriorityInitialized(CivController civ)
        {
            if (civ.CivData.SharedBranchPriority != null && civ.CivData.SharedBranchPriority.Count == SharedFields.Length)
                return;
            civ.CivData.SharedBranchPriority = new List<TechFieldEnum>(SharedFields);
        }

        /// <summary>
        /// Returns this civ's current 1st-5th shared-branch priority, seeding it with the default
        /// declaration order the first time it's read if the civ hasn't set one yet - lets the
        /// ranking UI (§8 II.4) safely read/display this before ProcessResearchForAllCivs has ever
        /// run a tick for this civ (e.g. the very first turn).
        /// </summary>
        public List<TechFieldEnum> GetSharedBranchPriority(CivController civ)
        {
            if (civ?.CivData == null) return new List<TechFieldEnum>(SharedFields);
            EnsureBranchPriorityInitialized(civ);
            return civ.CivData.SharedBranchPriority;
        }

        /// <summary>Applies a civ's free Tier-0 Branch F ability once, the first time this civ is
        /// ever processed (§5) - InnateFromStart techs never enter the research queue at all.</summary>
        private void EnsureInnateTechApplied(CivController civ)
        {
            if (!uniqueDefsByCiv.TryGetValue(civ.CivData.CivEnum, out var list)) return;

            TechDefSO innate = list.Find(d => d.UnlockMode == TechUnlockMode.InnateFromStart);
            if (innate == null || civ.CivData.ResearchedTechIds.Contains(innate.Id)) return;

            civ.CivData.ResearchedTechIds.Add(innate.Id);
            ApplyTechEffect(civ, innate);
            Debug.Log($"🔬 {civ.CivData.CivShortName} starts with innate '{innate.DisplayName}'.");
        }

        /// <summary>
        /// Splits this turn's TechPoints income across Branch F (always-on) and the civ's ranked
        /// shared branches per §2a's weight curve, banking each share against that branch's current
        /// GetBranchTarget. A branch with no target (fully researched) drops out of the split for
        /// that turn and its share redistributes proportionally across the remaining live targets.
        /// A target completes once its bank covers its ResearchCost AND its TechPointsThreshold has
        /// cleared - a branch pre-banking against a still tier-locked tech sits fully-funded-and-
        /// waiting rather than completing early.
        /// </summary>
        private void ApplyBranchPriorityIncome(CivController civ, int techPointsGained)
        {
            if (techPointsGained <= 0) return;
            EnsureLookupsBuilt();
            if (techDefsById.Count == 0) return; // TechDefSO list not populated yet in this scene

            EnsureInnateTechApplied(civ);
            EnsureBranchPriorityInitialized(civ);

            var weighted = new List<(TechDefSO target, float weight)>();

            TechDefSO factionTarget = GetBranchTarget(civ, TechFieldEnum.FactionUnique);
            if (factionTarget != null) weighted.Add((factionTarget, FactionUniqueShare));

            var priority = civ.CivData.SharedBranchPriority;
            for (int i = 0; i < priority.Count && i < RankShares.Length; i++)
            {
                TechDefSO target = GetBranchTarget(civ, priority[i]);
                if (target != null) weighted.Add((target, RankShares[i]));
            }

            float totalWeight = weighted.Sum(w => w.weight);
            if (totalWeight <= 0f) return; // every branch + Branch F fully researched

            foreach (var (target, weight) in weighted)
            {
                int share = Mathf.RoundToInt(techPointsGained * (weight / totalWeight));
                if (share <= 0) continue;

                int banked = civ.CivData.BankedTechPointsByTechId.TryGetValue(target.Id, out int existing) ? existing : 0;
                banked += share;
                civ.CivData.BankedTechPointsByTechId[target.Id] = banked;

                if (banked >= target.ResearchCost && civ.CivData.TechPoints >= target.TechPointsThreshold)
                    CompleteResearch(civ, target);
            }
        }

        /// <summary>
        /// Phase II effect wiring (§6, §8 II.3) is not implemented yet - every TechEffectHook this
        /// dispatches to is still a logging no-op. Hooking each into ShipStatCalculator/
        /// CombatOrderHelper/ResearchCenterData/etc. per §5a's mapping is future work; this stub
        /// exists so CompleteResearch has a single call site to wire up later, per §6.
        /// </summary>
        private void ApplyTechEffect(CivController civ, TechDefSO def)
        {
            Debug.Log($"ApplyTechEffect (stub - §8 II.3 not implemented): {civ.CivData.CivShortName} → {def.EffectHook}");
        }

        private void CompleteResearch(CivController civ, TechDefSO def)
        {
            civ.CivData.ResearchedTechIds.Add(def.Id);
            civ.CivData.BankedTechPointsByTechId.Remove(def.Id);

            if (civ.CivData.ManualTechPinByField != null &&
                civ.CivData.ManualTechPinByField.TryGetValue(def.Field, out string pinnedId) && pinnedId == def.Id)
            {
                civ.CivData.ManualTechPinByField.Remove(def.Field); // pin consumed - branch reverts to its natural pick
            }

            ApplyTechEffect(civ, def);
            OnTechResearched?.Invoke(civ, def);

            Debug.Log($"🔬 {civ.CivData.CivShortName} completed '{def.DisplayName}' ({def.Field} T{def.Tier}).");
            if (GameController.Instance.AreWeLocalPlayer(civ.CivData.CivEnum))
                Debug.Log($"PLAYER NOTIFICATION: Research complete - {def.DisplayName}!");
                // TechNotificationUI.Instance?.ShowTechResearched(civ, def); - wire up once II.4 UI exists.
        }

        /// <summary>Fired when a specific tech completes (additive to the legacy level-up
        /// OnTechAdvanced event above, which keeps firing unchanged, §2a).</summary>
        public event System.Action<CivController, TechDefSO> OnTechResearched;

        // ═══════════════════════════════════════════════════════════════════════════════════════

        // Fog-of-war sight range grows in 7 discrete stages as a civ earns TechPoints, to read
        // as stepped sensor/scanner breakthroughs rather than smooth growth. Stage 1 (0 points,
        // start of EARLY) sits at ~1/3 of FleetManager.LocalPlayerFogSightRange; stage 7 (900
        // points, within SUPREME) sits at 2x - deliberately short of the ~1000-point effective
        // cap CivData.TechRating clamps to, so the final stage still reads as an earned reward
        // rather than an automatic end-state. Boundaries otherwise line up with
        // CivData.TechThresholds (0/100/300/600), each level split into one extra mid-level step.
        private static readonly (int TechPointsRequired, float Multiplier)[] fogSightRangeStages =
        {
            (0,   1f / 3f),
            (100, 0.6111f),
            (200, 0.8889f),
            (300, 1.1667f),
            (450, 1.4444f),
            (600, 1.7222f),
            (900, 2f),
        };

        /// <summary>
        /// Returns the fog-of-war sight range multiplier for the given TechPoints total,
        /// stepping up at each of the 7 stages defined in fogSightRangeStages.
        /// </summary>
        public float GetFogSightRangeMultiplier(int techPoints)
        {
            float multiplier = fogSightRangeStages[0].Multiplier;

            foreach (var stage in fogSightRangeStages)
            {
                if (techPoints >= stage.TechPointsRequired)
                    multiplier = stage.Multiplier;
            }

            return multiplier;
        }

        /// <summary>
        /// Returns the actual fog-of-war sight range (world units) for the given TechPoints
        /// total, scaling FleetManager.LocalPlayerFogSightRange by the current stage multiplier.
        /// </summary>
        public int GetFogSightRange(int techPoints)
        {
            return Mathf.RoundToInt(FleetManager.LocalPlayerFogSightRange * GetFogSightRangeMultiplier(techPoints));
        }

        // Cached so RefreshLocalPlayerFogSightRangeIfChanged only touches csFogWar (and forces
        // a recompute) on an actual stage change, not on every single TechPoints-mutating call.
        private int lastAppliedLocalFogSightRange = -1;

        /// <summary>
        /// Re-applies the local player's current fog sight range to every registered FogRevealer
        /// if their stage has changed since the last check. Every FogRevealer in the game belongs
        /// to the local player (see FleetManager.RegisterFleetControllerAndSetupVisuals and
        /// StarSysManager.InstantiateSystem - only local-player fleets/systems ever get one), so
        /// a stage change applies uniformly to all of them. Call this after any code path that
        /// may have changed the local player's TechPoints.
        /// </summary>
        private void RefreshLocalPlayerFogSightRangeIfChanged()
        {
            CivController localCiv = CivManager.Instance?.LocalPlayerCivController;
            if (localCiv?.CivData == null) return;

            int desiredSightRange = GetFogSightRange(localCiv.CivData.TechPoints);
            if (desiredSightRange == lastAppliedLocalFogSightRange) return;

            csFogWar fogWar = csFogWar.Instance;
            // Not ready yet (e.g. still mid-scene-load) - leave lastAppliedLocalFogSightRange
            // untouched so this retries on the next mutation instead of silently giving up.
            if (fogWar == null || !fogWar.FogReady) return;

            lastAppliedLocalFogSightRange = desiredSightRange;

            foreach (var revealer in fogWar._FogRevealers)
            {
                revealer.SetSightRange(desiredSightRange);
            }

            fogWar.ForceUpdateFog();
        }

        private void Awake()
        {
            ServiceLocator.Register<TechManager>(this);
            if (Instance == null)
            {
                Instance = this;
                DontDestroyOnLoad(gameObject);
            }
            else
            {
                Destroy(gameObject);
            }
        }

        // Tech is processed once per turn via TimeManager.ProcessTurnEvents → ProcessResearchForAllCivs.
        // No per-stardate hook needed; subscribing per-stardate would add points 10× per turn.

        // Minor races have no player driving their research choices, so - unlike the majors above -
        // they always earn at least a small trickle of TechPoints every turn regardless of whether
        // the (AI-managed) system ever gets around to building a Research Center. This is what keeps
        // a minor race's tech progressing on its own timeline instead of stalling at 0 forever if
        // StarSysAIManager's economy priorities never reach ResearchCenter for it (see
        // ResearchCenterGateFactories/ResearchCenterGateShipyards in StarSysAIManager - a fresh
        // colony-tier minor can go a long time before qualifying).
        private const int BaseMinorTechPerTurn = 1;

        /// <summary>
        /// Advances every non-playable (minor) civ's TechPoints by its own turn's research output -
        /// entirely independent of the local human player's own tech gain (that coupling used to
        /// exist here and made every minor race's tech rise and fall with the human's pace instead
        /// of its own economy). Two additive sources, both scaled by <see cref="CivSO.QualityScore"/>
        /// via <see cref="ShipStatCalculator.GetQualityScaleFactor"/> (the same 0.70x-1.30x curve
        /// used for that minor's ships) so a canonically advanced minor (e.g. Breen, Tholian)
        /// researches faster than a canonically primitive one (e.g. Pakled, Kazon) even before
        /// either has built a single facility:
        ///   • BaseMinorTechPerTurn - a flat passive trickle, always earned.
        ///   • Its own active Research Centers - same per-center rate and tech-level multiplier the
        ///     majors use (CountActiveResearchCenters/GetResearchOutputMultiplier), since minors are
        ///     AI-managed (StarSysAIManager) and can build Research Centers within their own
        ///     QualityScore-scaled facility cap just like any AI-run system.
        /// Pre-warp civs and uninhabited placeholders never progress (HasWarp gate, unchanged from
        /// before).
        /// </summary>
        private void ProcessMinorRaceResearch()
        {
            foreach (var civ in CivManager.Instance.CivControllersInGame)
            {
                if (civ?.CivData == null) continue;
                if (civ.CivData.Playable) continue;   // playable civs handled in the pass above
                if (!civ.CivData.HasWarp) continue;   // pre-warp and uninhabited placeholders do not progress

                TechLevel levelBefore = civ.CivData.CurrentTechLevel;
                float qualityScale = ShipStatCalculator.GetQualityScaleFactor(civ.CivData.QualityScore);
                float researchMultiplier = GetResearchOutputMultiplier(levelBefore);
                int activeResearchCenters = CountActiveResearchCenters(civ);

                int techPointsGained = Mathf.Max(1, Mathf.RoundToInt(
                    (BaseMinorTechPerTurn + activeResearchCenters * techPointsPerResearchCenterPerTurn * researchMultiplier)
                    * qualityScale));

                civ.CivData.TechPoints += techPointsGained;

                if (civ.CivData.CurrentTechLevel > levelBefore)
                    OnTechLevelAdvanced(civ, civ.CivData.CurrentTechLevel);
            }
        }
        private void OnTechLevelAdvanced(CivController civ, TechLevel newLevel)
        {
            Debug.Log($"{civ.CivData.CivLongName} advanced to {newLevel}!");
            OnTechAdvanced?.Invoke(civ, newLevel);

            // Immediately swap the shipyard palette (icons/build-times/locked state) if this
            // civ's build menu happens to be open right now - otherwise it wouldn't refresh
            // until the player closed and reopened it.
            TimeManager.Instance?.RefreshBuildUIsForCiv(civ.CivData.CivEnum);

            if (GameController.Instance.AreWeLocalPlayer(civ.CivData.CivEnum))
            {
                TechNotificationUI.Instance?.ShowTechAdvancement(civ, newLevel);
                Debug.Log($"PLAYER NOTIFICATION: You advanced to {newLevel}!");
            }
        }
        private int CountActiveResearchCenters(CivController civ)
        {
            int count = 0;

            // StarSysWeOwn is only assigned once a civ is given a home system
            // (CivManager.AddSystemToOwnSystemListAndHomeSys) - it stays null otherwise,
            // so guard it here the same way every other reader of this list does.
            if (civ.CivData.StarSysWeOwn == null) return count;

            foreach (var system in civ.CivData.StarSysWeOwn)
            {
                if (system?.StarSysData == null) continue;

                // Count research centers that are turned ON (text = "1")
                foreach (var researchCenter in system.StarSysData.ResearchCenters)
                {
                    if (researchCenter?.GetComponent<TMPro.TextMeshProUGUI>()?.text == "1")
                    {
                        count++;
                    }
                }
            }

            return count;
        }

        /// <summary>
        /// Returns build speed multiplier for factories based on tech level.
        /// Higher tech = faster building (lower build time).
        /// </summary>
        public float GetFactorySpeedMultiplier(TechLevel techLevel)
        {
            switch (techLevel)
            {
                case TechLevel.EARLY:
                    return 1.0f; // Base speed
                case TechLevel.DEVELOPED:
                    return 1.25f; // 25% faster
                case TechLevel.ADVANCED:
                    return 1.5f; // 50% faster
                case TechLevel.SUPREME:
                    return 2.0f; // 2x faster
                default:
                    return 1.0f;
            }
        }

        /// <summary>
        /// Returns build speed multiplier for shipyards based on tech level.
        /// </summary>
        public float GetShipyardSpeedMultiplier(TechLevel techLevel)
        {
            switch (techLevel)
            {
                case TechLevel.EARLY:
                    return 1.0f;
                case TechLevel.DEVELOPED:
                    return 1.3f; // 30% faster
                case TechLevel.ADVANCED:
                    return 1.6f; // 60% faster
                case TechLevel.SUPREME:
                    return 2.2f; // 2.2x faster (shipyards benefit more from tech)
                default:
                    return 1.0f;
            }
        }

        /// <summary>
        /// Returns build speed multiplier for other facilities (shields, batteries, research).
        /// </summary>
        public float GetFacilitySpeedMultiplier(TechLevel techLevel)
        {
            switch (techLevel)
            {
                case TechLevel.EARLY:
                    return 1.0f;
                case TechLevel.DEVELOPED:
                    return 1.2f; // 20% faster
                case TechLevel.ADVANCED:
                    return 1.4f; // 40% faster
                case TechLevel.SUPREME:
                    return 1.8f; // 80% faster
                default:
                    return 1.0f;
            }
        }

        /// <summary>
        /// Returns research output multiplier based on tech level.
        /// Higher tech = more efficient research centers.
        /// </summary>
        public float GetResearchOutputMultiplier(TechLevel techLevel)
        {
            switch (techLevel)
            {
                case TechLevel.EARLY:
                    return 1.0f;
                case TechLevel.DEVELOPED:
                    return 1.5f; // 50% more research output
                case TechLevel.ADVANCED:
                    return 2.0f; // 2x output
                case TechLevel.SUPREME:
                    return 3.0f; // 3x output
                default:
                    return 1.0f;
            }
        }

        /// <summary>
        /// Generic tech multiplier for stats (ship speed, weapons, shields, etc.)
        /// </summary>
        public float GetTechMultiplier(TechLevel techLevel)
        {
            switch (techLevel)
            {
                case TechLevel.EARLY:
                    return 1.0f; // Base stats
                case TechLevel.DEVELOPED:
                    return 1.15f; // +15%
                case TechLevel.ADVANCED:
                    return 1.35f; // +35%
                case TechLevel.SUPREME:
                    return 1.6f; // +60%
                default:
                    return 1.0f;
            }
        }

        /// <summary>
        /// Returns power efficiency multiplier based on tech level.
        /// Higher tech = more efficient power usage (lower consumption).
        /// </summary>
        public float GetPowerEfficiencyMultiplier(TechLevel techLevel)
        {
            switch (techLevel)
            {
                case TechLevel.EARLY:
                    return 1.0f; // Base power consumption
                case TechLevel.DEVELOPED:
                    return 0.9f; // 10% less power needed
                case TechLevel.ADVANCED:
                    return 0.8f; // 20% less power
                case TechLevel.SUPREME:
                    return 0.7f; // 30% less power
                default:
                    return 1.0f;
            }
        }

        /// <summary>
        /// Add research points to a civilization and check for advancement.
        /// Called by UI or other systems.
        /// </summary>
        public void AddResearchPoints(CivController civ, int points)
        {
            if (civ?.CivData == null) return;

            TechLevel levelBefore = civ.CivData.CurrentTechLevel;
            civ.CivData.TechPoints += points;
            Debug.Log($"{civ.CivData.CivShortName}: +{points} tech points (total: {civ.CivData.TechPoints})");

            if (civ.CivData.CurrentTechLevel > levelBefore)
                OnTechLevelAdvanced(civ, civ.CivData.CurrentTechLevel);

            RefreshLocalPlayerFogSightRangeIfChanged();
        }

        /// <summary>
        /// Returns progress (0-1) to the next tech level.
        /// </summary>
        public float GetProgressToNextLevel(CivData civData)
        {
            if (civData == null) return 0f;

            TechLevel currentLevel = civData.CurrentTechLevel;
            TechLevel nextLevel = GetNextTechLevel(currentLevel);

            if (nextLevel == currentLevel) // Already at max
                return 1f;

            int currentThreshold = CivData.TechThresholds[currentLevel];
            int nextThreshold = CivData.TechThresholds[nextLevel];
            int pointsNeeded = nextThreshold - currentThreshold;
            int pointsEarned = civData.TechPoints - currentThreshold;

            return Mathf.Clamp01((float)pointsEarned / pointsNeeded);
        }

        /// <summary>
        /// Gets the next tech level after the given one.
        /// </summary>
        private TechLevel GetNextTechLevel(TechLevel current)
        {
            switch (current)
            {
                case TechLevel.EARLY:
                    return TechLevel.DEVELOPED;
                case TechLevel.DEVELOPED:
                    return TechLevel.ADVANCED;
                case TechLevel.ADVANCED:
                    return TechLevel.SUPREME;
                case TechLevel.SUPREME:
                    return TechLevel.SUPREME; // Already at max
                default:
                    return TechLevel.EARLY;
            }
        }

        /// <summary>
        /// Event triggered when a civilization advances to a new tech level.
        /// Make this public so UI can subscribe.
        /// </summary>
        public event System.Action<CivController, TechLevel> OnTechAdvanced;

        /// <summary>
        /// Called when tech level advances - trigger event and notifications.
        /// </summary>
        //private void OnTechLevelAdvanced(CivController civ, TechLevel newLevel)
        //{
        //    Debug.Log($"🎉 {civ.CivData.CivLongName} advanced to {newLevel}!");

        //    // Trigger event for UI and other systems
        //    OnTechAdvanced?.Invoke(civ, newLevel);

        //    // Show notification to local player
        //    if (GameController.Instance.AreWeLocalPlayer(civ.CivData.CivEnum))
        //    {
        //        TechNotificationUI.Instance?.ShowTechAdvancement(civ, newLevel);
        //    }
        //}

        /// <summary>
        /// Manually process research for all civilizations (called each turn/stardate).
        /// </summary>
        public void ProcessResearchForAllCivs()
        {
            foreach (var civ in CivManager.Instance.CivControllersInGame)
            {
                if (civ?.CivData == null) continue;
                if (!civ.CivData.Playable) continue;

                int activeResearchCenters = CountActiveResearchCenters(civ);
                if (activeResearchCenters == 0) continue;

                TechLevel levelBefore    = civ.CivData.CurrentTechLevel;
                float researchMultiplier = GetResearchOutputMultiplier(levelBefore);
                int techPointsGained     = Mathf.RoundToInt(activeResearchCenters * techPointsPerResearchCenterPerTurn * researchMultiplier);

                civ.CivData.TechPoints += techPointsGained;
                Debug.Log($"{civ.CivData.CivShortName}: +{techPointsGained} tech points " +
                         $"({activeResearchCenters} centers × {researchMultiplier:F1}x = total: {civ.CivData.TechPoints})");

                if (civ.CivData.CurrentTechLevel > levelBefore)
                    OnTechLevelAdvanced(civ, civ.CivData.CurrentTechLevel);

                // Phase II (§2a, additive - CivData.TechPoints above is unchanged Phase I currency):
                // the same turn's income also banks toward the civ's branch-priority research picks.
                ApplyBranchPriorityIncome(civ, techPointsGained);
            }

            // Simulated independently of the local player's own tech gain - see
            // ProcessMinorRaceResearch's comment for why that coupling was removed.
            ProcessMinorRaceResearch();

            RefreshLocalPlayerFogSightRangeIfChanged();
        }


        private void OnDestroy()
        {
            ServiceLocator.Unregister<TechManager>();
        }
}
}